
library(httr)
library(jsonlite)
library(tidyverse)
library(lubridate)

# 2. Set your Bearer Token exactly as shown in the portal
bearer <- "AAAAAAAAAAAAAAAAAAAAADYowgAAAAAADFWlIaqB6aS2vRujARBXglBbHWc%3DCzD5sUy3gEuhWtyYOucS9yuCQURiSzTikO5ujzpIkXKZfoDPlC"
hdr    <- add_headers(Authorization = paste0("Bearer ", bearer))

# 3. Lookup your user ID & profile metrics
user_res <- GET(
  "https://api.twitter.com/2/users/by/username/EGRISStats",
  hdr,
  query = list("user.fields" = "public_metrics")
)
stop_for_status(user_res)
user_data <- content(user_res, simplifyVector = TRUE)$data

user_id          <- user_data$id
author_followers <- user_data$public_metrics$followers_count

cat("User ID: ", user_id, "\n",
    "Followers:", author_followers, "\n\n")

# 4. Fetch up to 100 of your most recent tweets with engagement counts
tweets_res <- GET(
  sprintf("https://api.twitter.com/2/users/%s/tweets", user_id),
  hdr,
  query = list(
    max_results    = 100,
    "tweet.fields" = "created_at,public_metrics"
  )
)
stop_for_status(tweets_res)
tweets_data <- content(tweets_res, simplifyVector = TRUE)$data

# 5. Tidy into tibble & unpack metrics
tweets_df <- as_tibble(tweets_data) %>%
  rename(status_id = id) %>%
  unnest_wider(public_metrics) %>%
  mutate(
    created_at   = ymd_hms(created_at),
    interactions = retweet_count + like_count
  )

# 6. Basic summaries
cat("Interactions (retweets+likes) summary:\n")
print(summary(tweets_df$interactions))

cat("\nAverage interactions per tweet: ",
    round(mean(tweets_df$interactions),1), "\n")

cat("Mean interactions per follower: ",
    round(mean(tweets_df$interactions) / author_followers, 6), "\n\n")

# ─────────────────────────────────────────────────────────────────────────────
# Prereqs: you’ve already done steps 1–6 and have `tweets_df` and `author_followers`
# ─────────────────────────────────────────────────────────────────────────────

# 7. Detailed time-series plot of interactions
library(ggplot2)

tweets_df <- tweets_df %>%
  mutate(date = as.Date(created_at))

p_interactions <- ggplot(tweets_df, aes(x = date, y = interactions)) +
  geom_jitter(width = 0.2, alpha = 0.6, color = "steelblue") +
  geom_smooth(method = "loess", se = FALSE, color = "firebrick") +
  labs(
    title    = "Interactions on @EGRISStats Tweets Over Time",
    subtitle = sprintf("n = %d tweets; period: %s – %s",
                       nrow(tweets_df),
                       min(tweets_df$date),
                       max(tweets_df$date)),
    x        = "Date",
    y        = "Retweets + Likes"
  ) +
  theme_minimal(base_size = 14)

print(p_interactions)

# Save the plot
ggsave("interactions_time_series.png", p_interactions, width = 8, height = 5)

# 8. Save a small summary table to CSV
summary_df <- tibble(
  stat      = c("Min", "1st Qu.", "Median", "Mean", "3rd Qu.", "Max"),
  value     = as.numeric(c(
    min(tweets_df$interactions),
    quantile(tweets_df$interactions, .25),
    median(tweets_df$interactions),
    mean(tweets_df$interactions),
    quantile(tweets_df$interactions, .75),
    max(tweets_df$interactions)
  ))
)

write_csv(summary_df, "interaction_summary.csv")

# 9. Export everything into a Word document
library(officer)
library(flextable)

doc <- read_docx() %>%
  body_add_par("EGRISStats Tweet Interaction Analysis", style = "heading 1") %>%
  body_add_par(sprintf("Analysis run on %s", Sys.Date()), style = "Normal") %>%
  body_add_par("Profile Metrics", style = "heading 2") %>%
  body_add_par(sprintf("Followers: %s", scales::comma(author_followers)), style = "Normal") %>%
  body_add_par("Interaction Summary", style = "heading 2") %>%
  body_add_flextable(
    flextable(summary_df) %>%
      set_header_labels(stat = "Statistic", value = "Count") %>%
      theme_vanilla() %>%
      autofit()
  ) %>%
  body_add_par("Interactions Over Time", style = "heading 2") %>%
  body_add_img(src = "interactions_time_series.png", width = 6, height = 4) %>%
  body_add_par("Generated by your R analysis pipeline", style = "Normal")


print(doc, target = "EGRISStats_Interaction_Analysis.docx")

message("✅ All outputs saved:\n • interactions_time_series.png\n • interaction_summary.csv\n • EGRISStats_Interaction_Analysis.docx")


# ───────────────────────────────────────────────────────────────
# 0. Load libraries
# ───────────────────────────────────────────────────────────────
install.packages(c("httr","jsonlite","tidyverse","lubridate"))
library(httr)
library(jsonlite)
library(tidyverse)
library(lubridate)

# ───────────────────────────────────────────────────────────────
# 1. Your Bearer token (app-only)
# ───────────────────────────────────────────────────────────────
bearer <- "PASTE_YOUR_BEARER_TOKEN_HERE"
hdr    <- add_headers(Authorization = paste0("Bearer ", bearer))

# ───────────────────────────────────────────────────────────────
# 2. Helper to fetch & tidy one account
# ───────────────────────────────────────────────────────────────
fetch_tweets <- function(handle, n = 100) {
  # 2a) get user ID
  u <- GET(
    sprintf("https://api.twitter.com/2/users/by/username/%s", handle),
    hdr, query = list("user.fields" = "public_metrics")
  ) %>% stop_for_status() %>%
    content(simplifyVector=TRUE)$data
  
  uid <- u$id
  foll <- u$public_metrics$followers_count
  
  # 2b) get up to n tweets
  tw <- GET(
    sprintf("https://api.twitter.com/2/users/%s/tweets", uid),
    hdr, query = list(max_results = n, "tweet.fields" = "created_at,public_metrics")
  ) %>% stop_for_status() %>%
    content(simplifyVector=TRUE)$data
  
  # 2c) tidy into tibble
  df <- as_tibble(tw) %>%
    rename(status_id = id) %>%
    unnest_wider(public_metrics) %>%
    mutate(
      account      = handle,
      created_at   = ymd_hms(created_at),
      interactions = retweet_count + like_count,
      followers    = foll
    )
  return(df)
}

# ───────────────────────────────────────────────────────────────
# 3. Fetch both accounts
# ───────────────────────────────────────────────────────────────
handles <- c("EGRISStats","iascch")
tweets_all <- map_dfr(handles, fetch_tweets, n = 100)

# ───────────────────────────────────────────────────────────────
# 4. Comparative Summary
# ───────────────────────────────────────────────────────────────
summary_tbl <- tweets_all %>%
  group_by(account) %>%
  summarise(
    n_tweets      = n(),
    mean_int      = mean(interactions),
    median_int    = median(interactions),
    avg_eng_rate  = mean(interactions / followers)
  ) %>%
  arrange(desc(mean_int))

print(summary_tbl)

# ───────────────────────────────────────────────────────────────
# 5. Histogram of interactions (faceted)
# ───────────────────────────────────────────────────────────────
hist_plot <- ggplot(tweets_all, aes(interactions)) +
  geom_histogram(bins = 30, fill = "steelblue", alpha = 0.7) +
  scale_x_log10() +
  facet_wrap(~account) +
  labs(
    title = "Distribution of Retweets+Likes (log10)",
    x     = "Interactions (Retweets + Likes)",
    y     = "Tweet Count"
  ) +
  theme_minimal(base_size = 13)

print(hist_plot)
ggsave("compare_interactions_hist.png", hist_plot, width=8, height=4)

# ───────────────────────────────────────────────────────────────
# 6. Daily average interactions over time
# ───────────────────────────────────────────────────────────────
time_plot <- tweets_all %>%
  mutate(date = as_date(created_at)) %>%
  group_by(account, date) %>%
  summarise(avg_int = mean(interactions), .groups="drop") %>%
  ggplot(aes(date, avg_int, color = account)) +
  geom_line(size=1) +
  geom_smooth(method="loess", se=FALSE) +
  labs(
    title = "Daily Avg. Interactions per Tweet",
    x     = "Date",
    y     = "Avg (Retweets + Likes)"
  ) +
  theme_minimal(base_size = 13)

print(time_plot)
ggsave("compare_daily_interactions.png", time_plot, width=8, height=4)

# ───────────────────────────────────────────────────────────────
# 7. Save summary to CSV
# ───────────────────────────────────────────────────────────────
write_csv(summary_tbl, "compare_summary.csv")

message("✅ Finished. Outputs written to:\n",
        " • compare_summary.csv\n",
        " • compare_interactions_hist.png\n",
        " • compare_daily_interactions.png")

